Repository WGBH-MLA/sonyci, pull requests merged in 2023-05, with the labels that each got.

#3 🧼 Scrub
  tests/conftest.py
  tests/test_sonyci.py
  tests/vhs/test_sonyci/test_workspace.yaml
Labels: maintenance 🔧

#1 🛠️ Utils
  pdm.lock
  pyproject.toml
  sonyci/cli.py
  sonyci/config.py
  sonyci/sonyci.py
  sonyci/utils.py
  tests/ci.ipynb
  tests/test_sonyci.py
Labels: maintenance 🔧

#4 🕷 `urllib3` version bug
  pdm.lock
  pdm.toml
  pyproject.toml
Labels: bug 🐛

#5 🕵‍♀️ Secret scanning
  .pre-commit-config.yaml
  README.md
  pdm.lock
  pyproject.toml
Labels: enhancement ➕

#6 🛍 Get
  .gitignore
  pyproject.toml
  sonyci/_version.py
  sonyci/cli.py
  sonyci/sonyci.py
  tests/test_sonyci.py
  tests/vhs/test_sonyci/test_token.yaml
Labels: enhancement ➕

#7 📚 Docs
  .github/workflows/docs.yml
  .gitignore
  docs/index.md
  docs/install.md
  docs/reference/cli.md
  docs/reference/index.md
  docs/reference/sonyci.md
  mkdocs.yml
  overrides/main.html
  pdm.lock
  pyproject.toml
  sonyci/sonyci.py
Labels: documentation 📜

#11 ⏺️ Record
  tests/conftest.py
  tests/test_sonyci.py
Labels: enhancement ➕, test 🧪

#12 👩‍🔬️ CLI test
  .github/workflows/CI.yml
  tests/test_cli.py
  tests/vhs/tests.test_cli/test_bad_login.yaml
  tests/vhs/tests.test_cli/test_login.yaml
Labels: enhancement ➕, test 🧪

#13 🔍 Workspace search
  .vscode/settings.json
  sonyci/sonyci.py
  tests/sonyci/guid.toml
  tests/test_sonyci.py
  tests/vhs/tests.test_sonyci/test_workspace_contents.yaml
  tests/vhs/tests.test_sonyci/test_workspace_empty_search.yaml
  tests/vhs/tests.test_sonyci/test_workspace_search.yaml
Labels: test 🧪

#15 🍑 Assets
  sonyci/sonyci.py
  tests/test_sonyci.py
  tests/vhs/tests.test_sonyci/test_asset.yaml
Labels: enhancement ➕

#17 📬 CLI - Post
  sonyci/cli.py
  tests/test_cli.py
Labels: enhancement ➕

#20 💰 Inherit Codecov secrets
  .coveragerc
  .github/workflows/CI.yml
  README.md
  codecov.yml
  tests/test_cli.py
Labels: bug 🐛, test 🧪

#21 🏛 Publish
  .github/workflows/CI.yml
  .github/workflows/publish.yml
  sonyci/_version.py
  tests/__init__.py
  tests/sonyci/__init__.py
  tests/test_sonyci.py
Labels: CD 🏗️

#22 🚮 Un-reusable publish workflow
  .github/workflows/publish.yml
Labels: CD 🏗️, bug 🐛

#23 🏞 Path
  .github/workflows/publish.yml
Labels: CD 🏗️, bug 🐛

#24 🥃 dist
  .github/workflows/publish.yml
Labels: CD 🏗️

#25 🎙 mike
  pyproject.toml
Labels: CD 🏗️

#19 🔎 CLI id / secret
  sonyci/cli.py
  tests/cli/test_cli_login.py
Labels: enhancement ➕

#26 🛌 Fixes coverage
  .coveragerc
  pyproject.toml
  tests/__init__.py
Labels: bug 🐛, test 🧪

#18 ⚗️ CLI `login --test`
  .github/workflows/CI.yml
  pyproject.toml
  sonyci/cli.py
  sonyci/log.py
  sonyci/sonyci.py
  tests/cli/test_cli_login.py
  tests/cli/test_cli_search.py
  tests/conftest.py
  tests/test_cli.py
  tests/test_sonyci.py
  tests/vhs/test_cli_login/test_bad_login.yaml
  tests/vhs/test_cli_login/test_login.yaml
  tests/vhs/test_cli_search/test_empty_search.yaml
  tests/vhs/test_cli_search/test_guid_search.yaml
  tests/vhs/tests.test_sonyci/test_asset.yaml
  tests/vhs/tests.test_sonyci/test_asset_download.yaml
  tests/vhs/tests.test_sonyci/test_workspace.yaml
  tests/vhs/tests.test_sonyci/test_workspace_contents.yaml
  tests/vhs/tests.test_sonyci/test_workspace_empty_search.yaml
  tests/vhs/tests.test_sonyci/test_workspace_search.yaml
  tests/vhs/tests.test_sonyci/test_workspaces.yaml
Labels: bug 🐛

#28 🐳 Docker
  .github/workflows/CD.yml
  Dockerfile
Labels: CD 🏗️, enhancement ➕
